Update code samples for API v2
NebulousLabs/skynet-webportal pull request #381
Opened 2020-09-07 15:33 UTC by m-cat

2020-09-08 13:12 UTC, ro-tex requested changes
Looks good! Just two syntax errors in the `panic` calls in Go.

Btw, I see we have placeholders for PHP and Ruby. I'd be happy to write  a Ruby lib. Just ping me if you think that's a good idea.

2020-09-08 13:12 UTC, ro-tex commented on packages/webapp/src/components/CodeExamples/Code.js
> +		panic("Unable to upload: %v", err.Error())
req: Panic takes a single parameter.

```suggestion
		panic(fmt.Sprintf("Unable to upload: %v", err.Error()))
```

2020-09-08 13:12 UTC, ro-tex commented on packages/webapp/src/components/CodeExamples/Code.js
> +		panic("Something went wrong, please try again.\\nError: %v", err.Error())
```suggestion
		panic(fmt.Sprintf("Something went wrong, please try again.\nError: %v", err.Error()))
```

2020-09-08 14:55 UTC, m-cat commented
Thanks, fixed it so it matches the panics in the docs. The double backward-slashes are needed here.

> Btw, I see we have placeholders for PHP and Ruby. I'd be happy to write a Ruby lib. Just ping me if you think that's a good idea.

It's too much work for us to write, maintain and document for now. The priority going forwards is the skynet-js SDK.

2020-09-09 08:03 UTC, ro-tex approved these changes

2020-09-09 08:38 UTC, merged